name: Build Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "opentrader/cloud"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: pro.Dockerfile
          push: true
          tags: opentrader/opentrader:latest
          build-args: |
            ADMIN_PASSWORD=password
            GITHUB_TOKEN=${{ secrets.PRO_GITHUB_TOKEN }}
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
